[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["Aaditya Sahay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
rand = "0.3"
image = "*"